config/routes.rb
Rails.application.routes.draw do
  resources :messages
  resources :rooms
  resources :users
  
  root "rooms#index"
  get '/show_additionally', to: 'rooms#show_additionally'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room

  def previous
    Message.where(id: 1..self.id).order("id DESC").first
  end
 
  def next
    Message.where(id: self.id..1).order("id ASC").first
  end
end

app/models/room.rb
class Room < ApplicationRecord
    has_many :messages, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
    validates_uniqueness_of :username 

    def self.generate
        adjectives = ['Super', 'Hyper', 'Master', 'Ultra', 'Ultimate', 'Regular']
        nouns = ['Movie', 'Table', 'Computer', 'Food', 'Money']
        number = rand.to_s[2..4]
        username = "#{adjectives.sample}-#{nouns.sample}-#{number}"
        create(username: username)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user

    def current_user
        return @current_user if @current_user.present?

        if session[:user_id].present?
            @current_user = User.find(session[:user_id])
            @current_user
        else
            @current_user = User.generate
            session[:user_id] = @current_user.id
            @current_user
        end
    end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: %i[ show edit update ]

  # GET /messages or /messages.json
  def index
    @messages = Message.all
  end

  # GET /messages/new
  def new
    @message = Message.new
  end

  # POST /messages or /messages.json
  def create
    @message = Message.new(message_params)
    @message.user = current_user 
    @message.save

    SendMessageJob.perform_later(@message)
  end

  # PATCH/PUT /messages/1 or /messages/1.json
  def update
    respond_to do |format|
      if @message.update(message_params)
        format.html { redirect_to @message, notice: "Message was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_message
      @message = Message.find_by(id: params[:id])
    end

    # Only allow a list of trusted parameters through.
    def message_params
      params.require(:message).permit(:content, :user_id, :room_id)
    end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: %i[ show edit update destroy ]
  protect_from_forgery except: :show_additionally

  def first_room
    redirect_to "/rooms/#{Room.first.id}"
  end
  
  # GET /rooms or /rooms.json
  def index
    @rooms = Room.all.order(created_at: :desc)
  end
  
  # GET /rooms/1 or /rooms/1.json
  def show
    @last_messages = @room.messages.last(15)
    @user = User.find_by(id: current_user.id)
  end

  # GET/rooms/show_additionally?room_id=":id" sctollTOP => request AJAX
  # メッセージを上までスクロールしたらroom_channel.jsで設定した'scroll'イベントリスナーによってajaxによってこの関数が呼び出される
  # この後show_additionally.js.erbが実行される
  def show_additionally
    # 一番上のメッセージid取得
    last_id = params[:oldest_message_id].to_i
    #現在の部屋id取得
    room_id = Message.find(last_id).room_id
    # last_idとroom_idを使って、読み込みたい５件を取得
    @messages = Message.where(id: 1..last_id, room_id: room_id).where.not(id: last_id).last(5)
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # POST /rooms or /rooms.json
  def create
    @room = Room.new(room_params)
    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: "Room was successfully created." }
      else
        format.html { render :new , status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1 or /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: "Room was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1 or /rooms/1.json
  def destroy
    @room.destroy
    redirect_to rooms_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find_by(id: params[:id])
    end

    # Only allow a list of trusted parameters through.
    def room_params
      params.require(:room).permit(:name)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def update
    preveous_username = set_user.username
    respond_to do |format|
      if set_user.update!(user_params)
        format.js
      end
    end
    new_username = @user.username
    room_id_for_room_channel = @user.room_id
    ActionCable.server.broadcast "room_channel_#{room_id_for_room_channel}", preveous_username: preveous_username, new_username: new_username, data_type: "username"
  end


  private

  def set_user
    @user = User.find_by(id: current_user.id)
  end

  def user_params
    params.require(:user).permit(:username, :room_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
    def remove_zero(target_time) # => 例:引数"09:30" の場合
        
        split_time = target_time.split ":" # => ["09", "30"]
        hour = split_time[0] # => "09"
        minute = split_time[1] # => "30"
        split_hour = hour.split "" # => ["0", "9"]
        
        if split_hour[0] == "0" # => "時間:分"の時間の1の位が0の場合、取り除く
            hour = split_hour[1]
        end
        
        "#{hour}:#{minute}" # => "9:30"
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1, user-scalable=no">
    <title><%= yield(:title) %> | チャット</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/_form.html.erb
<%= form_for(message, remote: true) do |form| %>

<% if message.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(message.errors.count, "error") %> prohibited this message from being saved:</h2>

  <ul>
    <% message.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<%= form.hidden_field :room_id, value: room.id %>

<div class="input-group">
  <%= form.text_field  :content, class: 'form-control' %>
  <div class="input-group-append">
    <%= form.submit  "送信", class: "btn", id: "chat-btn", type: "hidden" %>
  </div>
</div>
<% end %>

app/views/messages/_message.html.erb
<div class="message mb-2 <%= 'me' if message.user == current_user %>" id="<%= message.id %>">
    <div class="content-container">
        <div class="content">
            <%= message.content %>
        </div>
        <div class="time">
            <%= remove_zero message.created_at.to_s(:time_jp) %>
        </div>
        <div class="author">
            <%= message.user.username %>　
        </div>
    </div>
</div>

app/views/messages/_mine.html.erb
<div class="message mb-2 me">
    <div class="content-container">
        <div class="content">
            <%= message.content %>
        </div>
        <div class="author">
            <%= message.user.username %>　
        </div>
        <div class="time">
            <%= remove_zero message.created_at.to_s(:time_jp) %>
        </div>
    </div>
</div>

app/views/messages/_theirs.html.erb
<div class="message mb-2">
    <div class="content-container">
        <div class="content">
            <%= message.content %>
        </div>
        <div class="author">
            <%= message.user.username %>
        </div>
        <div class="time">
            <%= remove_zero message.created_at.to_s(:time_jp) %>
        </div>
    </div>
</div>

app/views/messages/create.js.erb
var chatBox = document.getElementById('message_content');
chatBox.value = '';

var chatBtn = document.getElementById('chat-btn');
chatBtn.disabled = false;

app/views/messages/edit.html.erb
<h1>Editing Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Show', @message %> |
<%= link_to 'Back', messages_path %>

app/views/messages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Messages</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>User</th>
      <th>Room</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @messages.each do |message| %>
      <tr>
        <td><%= message.content %></td>
        <td><%= message.user_id %></td>
        <td><%= message.room_id %></td>
        <td><%= link_to 'Show', message %></td>
        <td><%= link_to 'Edit', edit_message_path(message) %></td>
        <td><%= link_to 'Destroy', message, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Message', new_message_path %>

app/views/messages/new.html.erb
<h1>New Message</h1>

<%= render 'form', message: @message %>

<%= link_to 'Back', messages_path %>

app/views/messages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @message.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @message.user_id %>
</p>

<p>
  <strong>Room:</strong>
  <%= @message.room_id %>
</p>

<%= link_to 'Edit', edit_message_path(@message) %> |
<%= link_to 'Back', messages_path %>

app/views/rooms/_form.html.erb
<%= form_with(model: room, local: true) do |form| %>
  <% if room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
        <% room.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="actions">
  </div>
<% end %>

app/views/rooms/edit.html.erb
<% provide(:title, "部屋名編集") %>
<div class="container-fluid">
    <div class="row">
        <div class="col-12 index-header"></div>
        <div class="col-4">
        </div>
        <div class="col-4">
            <%= render 'form', room: @room %>
        </div>
        <div class="col-4"></div>
    </div>
</div>

app/views/rooms/index.html.erb
<% provide(:title, "部屋一覧") %>
<ul style="margin: 15px;">
</ul>
<div class="container-fluid">
  <div class="row">
    <div class="col-12 index-header"></div>
    <div class="col-4">
    </div>
    <div class="col-4">
      <%= render 'rooms/form', room: Room.new %>
      <ul>
        <% @rooms.each do |room| %>
        <li><%= link_to " - #{room.id} . #{room.name}", "/rooms/#{room.id}" %></li>
        <% end %>
      </ul>
    </div>
    <div class="col-4"></div>
  </div>
</div>

app/views/rooms/new.html.erb
<h1>New Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Back', rooms_path %>

app/views/rooms/show.html.erb
<% provide(:title, "#{@room.name}") %>
<%= javascript_pack_tag 'home/index' %>
<div id="room-id" data-room-id="<%= @room.try(:id) %>"></div>
<div id="user-id" data-user-id="<%= current_user.id %>"></div>
<div class="container-fluid">
  <div class="row">
    <div class="main-content">
      <% if @room.present? %>
      <div class="chat-room">
        <nav class="navbar">
          <div class="navbar-button">
            <%= link_to "部屋一覧", "/rooms" %>
          </div>

          <button type="button" class="btn username-button" data-toggle="modal" data-target="#usernameModal">
            名前変更
          </button>

          <!-- Modal -->
          <div class="modal" id="usernameModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-dialog-center" role="document">
              <div class="modal-content">
                <div class="modal-body">
                  <button class="modal-close-button" data-dismiss="modal"></button>
                  <%= render 'users/form' %>
                </div>
              </div>
            </div>
          </div>

        </nav>
        <div id="messages">
          <% @last_messages.each do |message| %>
          <%= render 'messages/message', message: message %>
          <% end %>
        </div>
        <div class="chat-box">
          <%= render 'messages/form', message: Message.new, room: @room %>
        </div>
      </div>
      <% end %>
    </div>
</div>

app/views/rooms/show_additionally.js.erb
//　rooms_controllerのshow_additionallyアクションが実行された後に、このファイルが実行される
// rooms_controllerで定義したインスタンス変数がここで使える

var messageContainer = document.getElementById("messages");

var messageHeight = messageContainer.scrollHeight
// 上からメッセージを追加
messageContainer.insertAdjacentHTML('afterbegin', "<%= j(render @messages) %>")
var newMessageHeight = messageContainer.scrollHeight
messageContainer.scrollBy(0, newMessageHeight - messageHeight)

// メッセージが存在するときだけ，更に読み込み可能とする
<% if @messages.present? %>
    showAdditionally = true
<% end %>

app/views/users/_form.html.erb
<%= form_with model: @user do |form| %>
  <%= form.text_field :username, class: "username-form" %>
  <%= form.hidden_field :room_id, value: @room.id %>
  <%= form.submit "更新", id: "username-form-submit"%>
<% end %>

app/views/users/update.js.erb
var nodes = document.querySelectorAll(".message.mb-2.me")
nodes.forEach( node => {
    node.querySelector(".author").innerText = document.querySelector(".username-form").value
})
document.querySelector(".modal-close-button").click()